name: (API) Continuous Integration

on:
  push:
    branches:
      - feature/paralel-testing
    paths:
      - "server/**"

jobs:
  determine-test-count:
    runs-on: ubuntu-latest
    outputs:
      test_matrix: ${{ steps.generate-matrix.outputs.test_matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Count test files and generate matrix
        id: generate-matrix
        run: |
          TEST_COUNT=$(ls server/__tests__/suites/integration | wc -l)
          TEST_ARRAY=$(seq -s ',' 0 $((TEST_COUNT - 1)) | sed 's/^/[/' | sed 's/$/]/')
          echo "test_matrix=$TEST_ARRAY" >> "$GITHUB_OUTPUT"

  test:
    needs: determine-test-count
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_instance: ${{ fromJson(needs.determine-test-count.outputs.test_matrix) }}
    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_DB: ${{ matrix.test_instance }}
      CORE_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ci-database-${{ matrix.test_instance }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm ci

      - name: Run type-checking
        run: npm run build

      - name: Run Integration Tests
        run: TEST_INSTANCE=${{ matrix.test_instance }} npm run test ci

  type-check-client-js:
    name: Type-check Client JS package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0

      - name: Install server dependencies
        run: cd server && npm ci

      - name: Install client-js dependencies
        run: cd client-js && npm ci

      - name: Build & Type Check
        run: cd client-js && npm run build
