name: (API) Continuous Integration

on:
  push:
    branches:
      - feature/paralel-testing
    paths:
      - "server/**"

jobs:
  discover-tests:
    name: Discover Integration Test Files
    runs-on: ubuntu-latest
    outputs:
      testFiles: ${{ steps.set-matrix.outputs.testFiles }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find Test Files
        id: set-matrix
        run: |
          TEST_FILES=$(find server/__tests__/suites/integration -type f -name "*.test.ts"
          echo "Found test files: $TEST_FILES"
          echo "testFiles=$TEST_FILES" >> $GITHUB_OUTPUT

  test:
    needs: discover-tests
    name: Run Test - ${{ matrix.testFiles }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testFiles: ${{ fromJson(needs.discover-tests.outputs.testFiles) }}
    defaults:
      run:
        working-directory: ./server
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm ci

      - name: Set Test Name (DB & Execution)
        run: |
          TEST_NAME=$(basename "${{ matrix.testFiles }}" .test.ts)
          echo $TEST_NAME
          echo "TEST_NAME=$TEST_NAME" >> $GITHUB_ENV
          echo "DB_NAME=testdb_${{ matrix.testFiles }}" >> $GITHUB_ENV

      - name: Calculate Redis Port
        run: |
          REDIS_PORT=$((7000 + RANDOM % 1000))
          echo "REDIS_PORT=$REDIS_PORT" >> $GITHUB_ENV

      - name: Set Database URL
        run: echo "CORE_DATABASE_URL=postgresql://postgres:postgres@localhost:5432/$DB_NAME" >> $GITHUB_ENV

      - name: Create Test Database
        run: |
          PGPASSWORD=postgres psql -U postgres -h localhost -p 5432 -c "CREATE DATABASE $DB_NAME;"

      - name: Start Redis Container
        run: docker run -d --name redis_$TEST_NAME -p $REDIS_PORT:6379 redis

      - name: Run Integration Test
        run: npm run test $TEST_NAME

  type-check-client-js:
    name: Type-check Client JS package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0

      - name: Install server dependencies
        run: cd server && npm ci

      - name: Install client-js dependencies
        run: cd client-js && npm ci

      - name: Build & Type Check
        run: cd client-js && npm run build
